name: Fast Forward Pull Request
on:
  pull_request:
    types: [closed]
jobs:
  fast-forward:
    # Only run if the PR was merged.
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if source branch exists
        id: check_branch
        run: |
          branch="${{ github.event.pull_request.head.ref }}"
          git ls-remote --exit-code --heads origin "$branch" || echo "::set-output name=exists::false"
          echo "::set-output name=exists::true"

      - name: Fast forward source branch
        if: steps.check_branch.outputs.exists == 'true'
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          branch: ${{ github.event.pull_request.head.ref }}
          comment: always
